name: Generate XML Sitemap

on:
  push:
    branches:
      - main

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4 # ভার্সন আপডেট করা হয়েছে
      with:
        fetch-depth: 0 

    - name: Generate XML Sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://islamiclight.in/
        sitemap-format: xml

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # টোকেন যুক্ত করা হয়েছে
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add sitemap.xml
        git commit -m "Automated sitemap update" || exit 0
        git push origin main
        
